name: Build the repository
on: [push]

# Force a specific Ubuntu version to ensure everyone gets the same version even during migrations of the default version
# Pick the right folder based on its existence (later exams have higher priority)
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Build and run checks
        run: for d in exam-3 exam-2 exam-1 mock; do
               if [ -d "$d" ]; then cd "$d"; break; fi;
             done;
             chmod +x .github-actions-build.sh;
             ./.github-actions-build.sh
