# DO NOT EDIT THIS FILE
# THIS FILE ENSURES THAT YOUR TESTS COMPILE EVEN IF WE REPLACE THE REST OF YOUR CODE WITH EMPTY IMPLEMENTATIONS
# YOU SHOULD NOT RUN IT ON YOUR MACHINE AS IT MOVES MULTIPLE FILES AROUND

cp -r src/main src/main.backup
cp -r src/smoke/* src/main

echo "---> Compiling your tests on dummy code"

gradle compileTestJava
status=$?

echo ""


rm -r src/main
mv src/main.backup src/main

if [ $status != 0 ]
then
  echo "!!!!!!!!!!!!!!!!!!!!! CRITICAL ERROR !!!!!!!!!!!!!!!!!!!!!!!!"
  echo "!!! SEVERE WARNING: YOUR TESTS DO NOT COMPILE ON OUR CODE !!!"
  echo "!!! We have tried compiling your tests using the default sources, but the tests did not compile."
  echo "!!! Make sure your tests only use methods that are declared in the interfaces"
  echo "!!!!!!!!!!!!!!!!!!!!! CRITICAL ERROR !!!!!!!!!!!!!!!!!!!!!!!!"
else
  echo "---> Good, your tests compile on dummy code :)"
fi

exit $status