/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ex1;

public class App {
    public static void main(String[] args) {
        Pizza cheesePizza = Pizza.createCheesePizza();
        Pizza clamPizza = Pizza.createClamPizza();
        Pizza pepperoniPizza = Pizza.createPepperoniPizza();
        Pizza veggiePizza = Pizza.createVeggiePizza();
    }
}
