/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ex4;

public class App {
    public static void main(String[] args) {
        // Create a Stark army
        // Army starkArmy = new Army(Some parameter to create stark army);
        // Create a Tyrell army
        // Army tyrellArmy = new Army(Some parameter to create stark army);
    }
}
