/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ex11;
import io.javalin.Javalin;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Javalin app = Javalin.create().start(7000);
        app.get("/", ctx -> ctx.result("Hello World"));
    }
}
