/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package two;

public class App {
    public static void main(String[] args) {
        Greeter.askForFirstName();
        Greeter.askForFullName();
        Greeter.askForLastName();
        Greeter.askForFullNameAndAge();
    }
}
