/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package four;

public class App {

    public static void main(String[] args) {
        Circle c = new Circle(1);
        System.out.println(c.area());
        c.setRadius(5);
        System.out.println(c.perimeter());
        System.out.println(c.area());
        System.out.println(c.arcLength(180));
    }
}
