/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package intellij;

public class App {

    public static void main(String[] args) {
        GoodClassName myClass = new GoodClassName("oh hey");
        System.out.println(myClass.longAndComplicatedMethod());
        myClass.multiplesOf2();
    }
}
