/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ex4;

public class App {
    public static void main(String[] args) {
        Army starkArmy = new Army(new HouseStark());
        Army tyrellArmy = new Army(new HouseTyrell());
    }
}
