/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ex2;

public class App {
    public static void main(String[] args) {
        Computer pc1 = new Computer("eWhackintosh", 8192, 512, 3.5, true, true, 0xffffff, 1920, 1080, true, true, true);
        System.out.println(pc1);
    }
}
