/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ex9;

public class App {
    public static void main(String[] args) {
        SwingObserverExample example = new SwingObserverExample();
        example.go();
    }
}
