/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package three;

public class App {

    public static void main(String[] args) {
        Satellite.prettyPrintMostPopularBeers();
        Hitparade.prettyPrintMostPopularSongs();
    }
}
